[package]
authors = ["Orual <orual@nonbinary.computer>"]
edition = "2021"
# If you change the name here, you must also do it in flake.nix (and run `cargo generate-lockfile` afterwards)
name = "pattern"
description = "A simple Rust project using Nix"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Core dependencies
dotenv = "0.15"
letta = { path = "../letta-rs" }
miette = { version = "7.6.0", features = ["fancy"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
sled = "0.34.7"
sqlx = { version = "0.8.6", features = [
    "runtime-tokio",
    "sqlite",
    "uuid",
    "chrono",
    "migrate",
] }
tokio = { version = "1.45.1", features = ["full"] }
tokio-stream = "0.1.17"
toml = "0.8"
tracing = "0.1.41"

# Optional dependencies
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk", branch = "main", optional = true }
serenity = { version = "0.12.4", optional = true }
async-trait = { version = "0.1.83", optional = true }
clap = { version = "4.5.0", features = ["derive"], optional = true }
tracing-subscriber = { version = "0.3.19", features = [
    "env-filter",
    "fmt",
], optional = true }
chrono = { version = "0.4.39", optional = true }
futures = { version = "0.3", optional = true }
schemars = "0.8.22"

[features]
default = []
# Enable Discord bot functionality
discord = ["dep:serenity"]
# Enable MCP server functionality
mcp = ["dep:rmcp", "dep:async-trait"]
# Enable SSE transport for MCP server
mcp-sse = ["mcp"]
# Binary support (logging, CLI args)
binary = ["dep:clap", "dep:tracing-subscriber", "dep:chrono", "dep:futures"]
# Full binary with all features
full = ["discord", "mcp", "binary"]

[[bin]]
name = "pattern"
path = "src/main.rs"
required-features = ["binary"]

[[bin]]
name = "mcp"
path = "src/bin/mcp.rs"
required-features = ["mcp", "binary"]

[[bin]]
name = "discord_bot"
path = "src/bin/discord_bot.rs"
required-features = ["discord", "binary"]
