# Pattern Configuration
# See pattern.toml.example for all options

[database]
path = "pattern.db"

[discord]
# Add your bot token here or use DISCORD_TOKEN env var
token = ""
respond_to_dms = true
respond_to_mentions = true
channel_id = 1327007975960740004

[letta]
# For local server (default):
base_url = "http://localhost:8000"
# For Letta Cloud:
# api_key = ""
# base_url = "https://api.letta.com"

[mcp]
enabled = false
transport = "stdio"

# That's it! Run with: cargo run --features full