# Pattern Configuration
# See pattern.toml.example for all options

[database]
path = "pattern.db"

[discord]
# Add your bot token here or use DISCORD_TOKEN env var
token = ""
respond_to_dms = true
respond_to_mentions = true
channel_id = 1327007975960740004

[letta]
# For local server (default):
base_url = "http://localhost:8000"
# For Letta Cloud:
# api_key = ""
# base_url = "https://api.letta.com"

[mcp]
enabled = false
transport = "stdio"

# Model capability configuration
[models.default]
routine = "google_ai/gemini-2.5-flash"
interactive = "google_ai/gemini-2.5-flash"
investigative = "google_ai/gemini-2.5-flash"
critical = "anthropic/claude-3-opus-20240229"
temperature = 0.7

# Partner configuration - pre-initialize constellations at boot
[partners]
[[partners.users]]
discord_id = "549170854458687509"
name = "Orual"
auto_initialize = true

# That's it! Run with: cargo run --features full
