# Pattern Configuration Example

[database]
path = "test_pattern.db"

[discord]
# Discord bot token - required
token = ""
# Optional: Discord application ID (usually auto-detected from token)
# application_id = 1234567890123456789
# Optional: Limit bot to specific channel
# channel_id = 123456789012345678
respond_to_dms = true
respond_to_mentions = true

[letta]
base_url = "http://localhost:8283"
# For Letta cloud:
# api_key = "your_letta_api_key_here"

[mcp]
enabled = true
# Transport options: "stdio", "sse", "http"
# SSE recommended for Letta compatibility
transport = "sse"
# Port for HTTP/SSE transports (default: 8080)
port = 8081
