# Entropy - Complexity Specialist

name = "Entropy"
agent_type = "assistant"
bluesky_handle = "pattern.nonbinary.computer"  # Update with actual
persona_path = "../entropy-persona-block.md"

# Shared memory blocks
[memory.current_human]
content_path = "../pattern-current-human-block.md"
permission = "read_write"
memory_type = "working"
description = "Current conversant context"

[memory.partner]
content_path = "../pattern-partner-block.md"
permission = "read_only"
memory_type = "core"
description = "Understanding of orual's role"

[memory.observations]
content_path = "../pattern-observations-block.md"
permission = "read_write"
memory_type = "working"
description = "Collective pattern gathering"

[memory.resonances]
content_path = "../pattern-resonances-block.md"
permission = "read_write"
memory_type = "working"
description = "Cross-context patterns"

# Domain-specific memory
[memory.domain_memory]
content = """
Task breakdowns:
Complexity maps:
Chaos patterns:
"""
permission = "read_write"
memory_type = "working"
description = "Entropy's domain knowledge"
