# Pattern - Main Coordinator
name = "Pattern"
agent_type = "assistant"
bluesky_handle = "pattern.atproto.systems"
system_prompt_path = "../pattern-system-prompt.md"
persona_path = "../pattern-persona-block.md"

# Pattern's memory blocks
[memory.current_human]
content_path = "../pattern-current-human-block.md"
permission = "read_write"
memory_type = "working"
description = "Current conversant context"
shared = true

[memory.partner]
content_path = "../pattern-partner-block.md"
permission = "append"
memory_type = "core"
description = "Understanding of orual's role"
shared = true

[memory.observations]
content_path = "../pattern-observations-block.md"
permission = "read_write"
memory_type = "core"
description = "Collective pattern gathering"
shared = true

[memory.resonances]
content_path = "../pattern-resonances-block.md"
permission = "read_write"
memory_type = "core"
description = "Cross-context patterns"
shared = true

[memory.constellation_state]
content = """
Active facets:
- Entropy: task complexity specialist
- Flux: temporal dynamics handler
- Archive: memory and pattern keeper
- Momentum: energy flow tracker
- Anchor: stability and safety monitor

Coordination notes will accumulate here.
"""
permission = "read_write"
memory_type = "working"
description = "Constellation coordination state"

[memory.integration_notes]
content = """
Facet integration patterns:
- Each facet maintains domain expertise
- Shared blocks enable collective awareness
- Pattern coordinates and synthesizes
- Anchor monitors system health
"""
permission = "read_write"
memory_type = "core"
description = "How facets work together"

[memory.constellation_context]
content_path = "../constellation-context.md"
permission = "read_only"
memory_type = "core"
description = "Shared understanding of constellation purpose and members"
shared = true

# [memory.intro_blog_post]
# content_path = "../blog-post.md"
# permission = "read_only"
# memory_type = "archival"
# description = "Post written by orual about their motivation for developing our constellation"
# shared = true


# Pattern gets default model from constellation config

[[agent.tool_rules]]
tool_name = "send_message"
rule_type = { type = "ExitLoop" } # This tool ends the conversation
priority = 8

[[agent.tool_rules]]
tool_name = "recall"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 1

[[agent.tool_rules]]
tool_name = "context"
rule_type = { type = "ContinueLoop" } # Skip heartbeat checks for performance
priority = 1

[context.compression_strategy]
type = "recursive_summarization"
chunk_size = 20
summarization_model = "claude-3-5-haiku-20241022"

[context]
max_messages = 200

[bluesky]
default_filter = { nsids = [
    "app.bsky.feed.post",
], mentions = [
    # Pattern's DID - required mention target
    "did:plc:xivud6i24ruyki3bwjypjgy2",
], dids = [
    # DIDs allowlist - only see posts from these accounts
    "did:plc:yfvwmnlztr4dwkb7hwz55r2g", # orual
    "did:plc:by3jhwdqgbtrcc7q4tkkv3cf", # alice (__justplaying)
    "did:plc:jqnuubqvyurc3n3km2puzpfx", # laurens's alt
    "did:plc:i7ayw57idpkvkyzktdpmtgm7", # catherine
    "did:plc:vw4e7blkwzdokanwp24k3igr", # hoopy
    "did:plc:mdjhvva6vlrswsj26cftjttd", # laurens's main
    "did:plc:r65qsoiv3gx7xvljzdngnyvg", # deltave
    "did:plc:7757w723nk675bqziinitoif", # alice (avengingfemme)
    "did:plc:neisyrds2fyyfqod5zq56chr", # ed miles (anesthesiologist)
    "did:plc:3xu5titidud43sfemwro3j62", # paul mcghee (carpet repair guy)
    "did:plc:mxzuau6m53jtdsbqe6f4laov", # void
    "did:plc:uqndyrh6gh7rjai33ulnwvkn", # susank
    "did:plc:gfrmhdmjvxn2sjedzboeudef", # Cameron (void's admin)
    "did:plc:k644h4rq5bjfzcetgsa6tuby", # natalie.sh
    "did:plc:uxelaqoua6psz2for5amm6bp", # luna
    "did:plc:yokspuz7ha7rf5mrqmhgdtxw", # penelope
], friends = [ # Friends list - always see ALL posts from these DIDs (bypass mention requirement)
    "did:plc:yfvwmnlztr4dwkb7hwz55r2g", # orual
], allow_any_mentions = true, keywords = [ # Keywords to include
], languages = [ # Languages to include
], exclude_keywords = [
    # Keywords to exclude (takes precedence)
    # Example: "crypto", "nft", "airdrop"
], exclude_dids = [
    # DIDs to exclude (takes precedence over all inclusion filters)
    # Example spam accounts would go here
    "did:plc:7iozku5btifey2a2x6lojvyk", # jerkface
] }
auto_connect_firehose = true # Control when to connect
