[package]
name = "pattern-core"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Core agent framework and memory system for Pattern"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }

# Database
surrealdb = { workspace = true }

# AI/LLM
genai = { workspace = true }

# HTTP client (for embeddings)
reqwest = { workspace = true, optional = true }

# Schema generation
schemars = { workspace = true }
compact_str = { version = "0.9.0", features = ["serde", "markup", "smallvec"] }
smallvec = { version = "1.15.1", features = ["serde"] }
dashmap = { version = "6.1.0", features = ["serde"] }


# Local crates (to be added later)
# pattern-nd = { path = "../pattern-nd", optional = true }

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.13"
pretty_assertions = "1.4"
tempfile = "3.0"


[features]
default = ["surreal-embedded", "embed-candle", "embed-cloud"]
nd = []                                                       # Enable neurodivergent features when pattern-nd is ready

# Database backends
surreal-embedded = ["surrealdb/kv-surrealkv"]
surreal-remote = ["surrealdb/protocol-ws", "surrealdb/protocol-http"]

# Embedding backends
embed-candle = []
embed-cloud = ["reqwest"]
embed-ollama = ["reqwest"]


[lints]
workspace = true
